config/routes.rb
Rails.application.routes.draw do
  # use this for "out-of-the-box" User table (email/password columns only)
  # devise_for :users
  # use this for modified versions of User table (more than email/password columns)
  # devise_for :users, :controllers => { registrations: 'registrations' }

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get "/" => "users#home"
  get "/home" => "users#home"
  get "/select_user/:id" => "user#select_user"


  devise_for :users
  resources :users, only: [:show, :edit, :update, :index]
  resources :photos
  resources :jobs
  resources :boats
  resources :ports

end

app/models/port.rb
class Port < ApplicationRecord
  belongs_to :photo
  has_many :jobs_as_origin, :class_name => 'Job', :foreign_key => 'origin_id'
  has_many :jobs_as_destination, :class_name => 'Job', :foreign_key => 'destination_id'
end

app/controllers/ports_controller.rb
class PortsController < ApplicationController
  before_action :set_port, only: [:show, :edit, :update, :destroy]

  # GET /ports
  # GET /ports.json
  def index
    @ports = Port.all
  end

  # GET /ports/1
  # GET /ports/1.json
  def show
    @ports = Port.all
  end

  # GET /ports/new
  def new
    @port = Port.new
    @photos = Photo.all
  end

  # GET /ports/1/edit
  def edit
  end

  # POST /ports
  # POST /ports.json
  def create
    @port = Port.new(port_params)

    respond_to do |format|
      if @port.save
        format.html { redirect_to @port, notice: 'Port was successfully created.' }
        format.json { render :show, status: :created, location: @port }
      else
        format.html { render :new }
        format.json { render json: @port.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ports/1
  # PATCH/PUT /ports/1.json
  def update
    respond_to do |format|
      if @port.update(port_params)
        format.html { redirect_to @port, notice: 'Port was successfully updated.' }
        format.json { render :show, status: :ok, location: @port }
      else
        format.html { render :edit }
        format.json { render json: @port.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ports/1
  # DELETE /ports/1.json
  def destroy
    @port.destroy
    respond_to do |format|
      format.html { redirect_to ports_url, notice: 'Port was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_port
      @port = Port.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def port_params
      params.require(:port).permit(:name, :latitude, :longitude, :photo_id)
    end
end

app/helpers/ports_helper.rb
module PortsHelper
end

app/views/ports/_form.html.erb
<%= form_with(model: port, local: true) do |form| %>
  <% if port.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(port.errors.count, "error") %> prohibited this port from being saved:</h2>

      <ul>
      <% port.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <% selected_photo = nil %>
  <% if @port[:photo_id] %>
       <% selected_photo = @port[:photo_id] %>
   <% end %>
   <% photo_name_ids = [] %>
   <% @photos.each do |photo| %>
       <% photo_name_ids << [photo[:title], photo[:id]] %>
   <% end %>
   <% puts "photo_name_ids: #{photo_name_ids.inspect}" %>
  <div class="actions">
    Photo: <%= form.select(:photo_id, options_for_select(photo_name_ids, selected_photo)) %>
  </div>

  <div class="actions">
    <div class="field">
      <%= label :name, :name %> <br />
      <%= form.text_field :name %> <br>
    </div>
    <div class="field">
      <%= label :latitude, :latitude %><br />
      <%= form.number_field :latitude %> <br>
    </div>
    <div class="field">
      <%= label :longitude, :longitude %><br />
      <%= form.number_field :longitude %> <br>
    </div>
    <%= form.submit %>
  </div>
<% end %>

app/views/ports/edit.html.erb
<h1>Editing Port</h1>

<%= render 'form', port: @port %>

<%= link_to 'Show', @port %> |
<%= link_to 'Back', ports_path %>

app/views/ports/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Ports</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Lat</th>
      <th>Long</th>
      <th>Photo</th>
      <th>Edit</th>
      <th>Destroy</th>
    </tr>
  </thead>

  <tbody>
    <% @ports.each do |port| %>
      <tr>
        <td><%= link_to port[:name], port_path(port) %></td>
        <td><%= port[:latitude] %></td>
        <td><%= port[:longitude] %></td>
        <td><%= port[:photo_id] %></td>
        <td><%= link_to 'E', edit_port_path(port) %></td>
        <td><%= link_to 'D', port, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Port', new_port_path %>

app/views/ports/new.html.erb
<h1>New Port</h1>

<%= render 'form', port: @port %>

<%= link_to 'Back', ports_path %>

app/views/ports/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_port_path(@port) %> |
<%= link_to 'Back', ports_path %>