config/routes.rb
Rails.application.routes.draw do
  # use this for "out-of-the-box" User table (email/password columns only)
  # devise_for :users
  # use this for modified versions of User table (more than email/password columns)
  # devise_for :users, :controllers => { registrations: 'registrations' }

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get "/" => "users#home"
  get "/home" => "users#home"
  get "/select_user/:id" => "user#select_user"


  devise_for :users
  resources :users, only: [:show, :edit, :update, :index]
  resources :photos
  resources :jobs
  resources :boats
  resources :ports

end

app/models/job.rb
class Job < ApplicationRecord
  belongs_to :client, :class_name => 'User'
  belongs_to :manager, :class_name => 'User'
  belongs_to :origin, :class_name => 'Port'
  belongs_to :destination, :class_name => 'Port'
  has_many :ports
  has_many :job_boats, dependent: :destroy
  has_many :boats, through: :job_boats, dependent: :destroy
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :set_job, only: [:show, :edit, :update, :destroy]

  # GET /jobs
  # GET /jobs.json
  def index
    puts "\n******* index all jobs *******"
    @jobs = Job.all
  end

  # GET /jobs/1
  # GET /jobs/1.json
  def show
    puts "\n******* show jobs *******"
  end

  # GET /jobs/new
  def new
    puts "\n******* new job*******"
    @job = Job.new
    @users = User.all
    @ports = Port.all
  end

  # GET /jobs/1/edit
  def edit
    puts "\n******* edit jobs *******"
    @users = User.all
    @ports = Port.all
  end

  # POST /jobs
  # POST /jobs.json
  def create
      puts "\n******* create *******"
      @job = Job.new(job_params)
      @users = User.all
      @ports = Port.all
      respond_to do |format|
          if @job.save(job_params)
              puts "******* JOB SAVED *******"
              format.html { redirect_to @job, notice: 'Job was successfully created.' }
          else
              puts "******* save FAILED *******"
              format.html { render :edit }
          end
      end
  end

  # PATCH/PUT /jobs/1
  # PATCH/PUT /jobs/1.json
  def update
      puts "\n******* update *******"
      respond_to do |format|
          if @job.update(job_params)
              puts "******* JOB UPDATED *******"
              format.html { redirect_to @job, notice: 'Job was successfully updated.' }
          else
              puts "******* update FAILED *******"
              format.html { render :edit }
          end
      end
  end

  # DELETE /jobs/1
  # DELETE /jobs/1.json
  def destroy
    @job.destroy
    respond_to do |format|
      format.html { redirect_to @job, notice: 'Job was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_job
      @job = Job.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def job_params
        puts "\n******* job_params *******"
        params.require(:job).permit({boat_ids: []}, :origin_id, :destination_id, :client_id, :manager_id, :name)
    end
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/jobs/_form.html.erb
<%= form_with(model: @job, local: true) do |form| %>
  <% if @job.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@job.errors.count, "error") %> prohibited this @job from being saved:</h2>

      <ul>
      <% @job.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <% selected_client = nil %>
  <% if @job[:client_id] %>
      <% selected_client = @job[:client_id] %>
  <% end %>
  <% selected_manager = nil %>
  <% if @job[:manager_id] %>
      <% selected_manager = @job[:manager_id] %>
  <% end %>
  <% selected_origin = nil %>
  <% if @job[:origin_id] %>
      <% selected_origin = @job[:origin_id] %>
  <% end %>
  <% selected_destination = nil %>
  <% if @job[:destination_id] %>
      <% selected_destination = @job[:destination_id] %>
  <% end %>

  <% user_ids = [] %>
  <% @users.each do |user| %>
      <% user_ids << [user[:firstname], user[:id]] %>
  <% end %>
  <% puts "user_ids: #{user_ids.inspect}" %>
  <% port_ids = [] %>
  <% @ports.each do |port| %>
      <% port_ids << [port[:name], port[:id]] %>
  <% end %>
  <% puts "port_ids: #{port_ids.inspect}" %>


  <div class="actions">
    <%= form.label :client_id %><br />
    <%= form.select(:client_id, options_for_select(user_ids, selected_client)) %></p>
    <%= form.label :manager_id %><br />
    <%= form.select(:manager_id, options_for_select(user_ids, selected_manager)) %></p>
    <%= form.label :origin_id %><br />
    <%= form.select(:origin_id, options_for_select(port_ids, selected_origin)) %></p>
    <%= form.label :destination_id %><br />
    <%= form.select(:destination_id, options_for_select(port_ids, selected_destination)) %></p>
    <%= form.label :containers %><br />
    <%= form.number_field :containers, autofocus: true %><br />
    <%= form.label :price_per_cont %><br />
    <%= form.number_field :price_per_cont, autofocus: true %><br />
    <%= form.label :total_price %><br />
    <%= form.number_field :total_price, autofocus: true %>

    <%= form.submit %>
  </div>
<% end %>

app/views/jobs/edit.html.erb
<h1>Editing Job</h1>

<%= render 'form', job: @job %>

<%= link_to 'Show', @job %> |
<%= link_to 'Back', jobs_path %>

app/views/jobs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Jobs</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @jobs.each do |job| %>
      <tr>
        <td><%= link_to 'Show', job %></td>
        <td><%= link_to 'Edit', edit_job_path(job) %></td>
        <td><%= link_to 'Destroy', job, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Job', new_job_path %>

app/views/jobs/new.html.erb
<h1>New Job</h1>

<%= render 'form', job: @job %>

<%= link_to 'Back', jobs_path %>

app/views/jobs/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_job_path(@job) %> |
<%= link_to 'Back', jobs_path %>