config/routes.rb
Rails.application.routes.draw do
  # use this for "out-of-the-box" User table (email/password columns only)
  # devise_for :users
  # use this for modified versions of User table (more than email/password columns)
  # devise_for :users, :controllers => { registrations: 'registrations' }

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get "/" => "users#home"
  get "/home" => "users#home"
  get "/select_user/:id" => "user#select_user"


  devise_for :users
  resources :users, only: [:show, :edit, :update, :index]
  resources :photos
  resources :jobs
  resources :boats
  resources :ports

end

app/models/boat.rb
class Boat < ApplicationRecord
  belongs_to :photo
  has_many :ports
  has_many :job_boats, dependent: :destroy
  has_many :jobs, through: :job_boats, dependent: :destroy

end

app/controllers/boats_controller.rb
class BoatsController < ApplicationController
  before_action :set_boat, only: [:show, :edit, :update, :destroy]

  # GET /boats
  # GET /boats.json
  def index
    @boats = Boat.all
  end

  # GET /boats/1
  # GET /boats/1.json
  def show
    puts "\n******** show boats *******"
  end

  # GET /boats/new
  def new
    @boat = Boat.new
    @photos = Photo.all
  end

  # GET /boats/1/edit
  def edit
    puts "\n******** edit boats *******"
    @photos = Photo.all
  end

  # POST /boats
  # POST /boats.json
  def create
    puts "\n******* create *******"
    @boat = Boat.new(boat_params)

    respond_to do |format|
      if @boat.save(boat_params)
        format.html { redirect_to @boat, notice: 'Boat was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /boats/1
  # PATCH/PUT /boats/1.json
  def update
    puts "\n******* update *******"
    respond_to do |format|
      if @boat.update(boat_params)
        format.html { redirect_to @boat, notice: 'Boat was successfully updated.' }
        format.json { render :show, status: :ok, location: @boat }
      else
        format.html { render :edit }
        format.json { render json: @boat.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /boats/1
  # DELETE /boats/1.json
  def destroy
    @boat.destroy
    respond_to do |format|
      format.html { redirect_to @boat, notice: 'Boat was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_boat
      puts "\n******** set_boat *******"
      @boat = Boat.find(params[:id])
      puts "@boat #{@boat.inspect}"
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def boat_params
      params.require(:boat).permit(:name, :location, :capacity, :speed, :photo_id)

    end
end

app/helpers/boats_helper.rb
module BoatsHelper
end

app/views/boats/_form.html.erb
<%= form_with(model: boat, local: true) do |form| %>
  <% if boat.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(boat.errors.count, "error") %> prohibited this boat from being saved:</h2>

      <ul>
      <% boat.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <% selected_photo = nil %>
  <% if @boat[:photo_id] %>
      <% selected_photo = @boat[:photo_id] %>
  <% end %>

  <% photo_title_ids = [] %>
  <% @photos.each do |photo| %>
      <% photo_title_ids << [photo[:title], photo[:id]] %>
  <% end %>
  <% puts "photo_title_ids: #{photo_title_ids.inspect}" %>


  <div class="actions">
      <%= form.label :name %><br />
      <%= form.text_field :name, autofocus: true %><br />
      <%= form.label :location %><br />
      <%= form.text_field :location, autofocus: true %><br />
      <%= form.label :capacity %><br />
      <%= form.number_field :capacity, autofocus: true %><br />
      <%= form.label :speed %><br />
      <%= form.number_field :speed, autofocus: true %><br><br>
      <%= form.select(:photo_id, options_for_select(photo_title_ids, selected_photo)) %></p>

    <%= form.submit %>
  </div>
<% end %>

app/views/boats/edit.html.erb
<h1>Editing Boat</h1>

<%= render 'form', boat: @boat %>

<%= link_to 'Show', @boat %> |
<%= link_to 'Back', boats_path %>

app/views/boats/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Boats</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Location</th>
      <th>Capacity</th>
      <th>Speed</th>
      <th>Photo</th>
      <th>Edit</th>
      <th>Delete</th>
    </tr>
  </thead>

  <tbody>
    <% @boats.each do |boat| %>
      <tr>
        <td><%= boat[:name] %></td>
        <td><%= boat[:location] %></td>
        <td><%= boat[:capacity] %></td>
        <td><%= boat[:speed] %></td>
        <td><%= boat[:photo_id] %></td>
        <td><%= link_to 'Show', boat_path(boat) %></td>
        <td><%= link_to 'Edit', edit_boat_path(boat) %></td>
        <td><%= link_to 'Destroy', boat, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Add a new boat', new_boat_path %>

app/views/boats/new.html.erb
<h1>New Boat</h1>

<%= render 'form', boat: @boat %>

<%= link_to 'Back', boats_path %>

app/views/boats/show.html.erb
<p id="notice"><%= notice %></p>

<%= @boat[:name] %>

<%= link_to 'Edit', edit_boat_path(@boat) %> |
<%= link_to 'Back', boats_path %>