config/routes.rb
Rails.application.routes.draw do
  # use this for "out-of-the-box" User table (email/password columns only)
  # devise_for :users
  # use this for modified versions of User table (more than email/password columns)
  # devise_for :users, :controllers => { registrations: 'registrations' }

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get "/" => "users#home"
  get "/home" => "users#home"
  get "/select_user/:id" => "user#select_user"


  devise_for :users
  resources :users, only: [:show, :edit, :update, :index]
  resources :photos
  resources :jobs
  resources :boats
  resources :ports

end

app/views/layouts/application.html.erb
<!DOCTYPE html>

<!-- <p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p> -->

<html>
  <head>
    <title>Shipping_project</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
  <h1 class="business_title">Cargo Shipping</h1>
  <div class="nav_bar">
    <div class="nav_btn">
      <%= link_to "Home", home_path %>
    </div>
    <div class="nav_btn">
      <%= link_to "Boats", boats_path %>
    </div>
    <div class="nav_btn">
      <%= link_to "Ports", ports_path %>
    </div>
    <div class="nav_btn">
      <%= link_to "Jobs", jobs_path %>
    </div>
  </div>
  <div class="person">
    <% if !current_user %>
      <%= link_to "Sign up", new_user_registration_path %>
      <%= link_to "Sign in", new_user_session_path %>
    <% else %>
      <%= link_to "Photos", photos_path %> <br>
      <%= link_to "Profile", user_path(current_user) %> <br>
      <%= link_to "Sign out", destroy_user_session_path, :method => :delete %>
      <%= link_to "All_users", users_path %>
        <%= current_user.email %>
      </div>
    <% end %>
  </div>
  <div id="yield_container">
  <%= yield %>
  </div>
    <div id="footer">
      <h1 class="contact_info"><p class="contact">Contact Us:</p>Contact Us: Email: Weshipawesomestuff@aol.com | Phone:1800-867-5309 | Fax: "Fax info" | Mailing address: 1600 Pennsylvania Ave NW, Washington, DC 20500</h1>
    </div>
  </body>
</html>